version: "3.8"

services: 
  node:
    container_name: professional-api
    build: .
    restart: unless-stopped
    volumes: 
      - .:/usr/server_container
      - /usr/server_container/node_modules
    ports:
      - 2000:2000
    links:
      - mongo

  mongo:
      container_name: professional-db
      image: mongo:latest
      ports:
        - 27017:27017
      volumes:
        - ./docker_seeds/data:/usr/server_container/seeds
        - ./docker_seeds/scripts:/docker-entrypoint-initdb.d

